package passwordreset

import "time"

// Token represents a one-time password reset or force-change token.
// source = "admin_reset": generated by an admin for a user to reset their password via link.
// source = "force_change": generated when a user with force_password_change=true logs in.
type Token struct {
	ID         string
	UserID     string
	TokenHash  string
	Source     string // "admin_reset" | "force_change"
	ExpiresAt  time.Time
	ConsumedAt *time.Time
	CreatedAt  time.Time
}

// IsValid returns true if the token has not been consumed and has not expired.
func (t *Token) IsValid() bool {
	return t.ConsumedAt == nil && time.Now().Before(t.ExpiresAt)
}
